# Generated by Django 5.1.15 on 2026-09-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdelivery',
            name='batch_claimed_at',
            field=models.DateTimeField(blank=True, help_text='Set by the digest sweep that owns this row; released if the sweep fails.', null=True),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='batch_queued_at',
            field=models.DateTimeField(blank=True, help_text='Set when this delivery was queued into an email digest instead of dispatched inline.', null=True),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['status', 'channel', 'batch_queued_at'], name='notificatio_status_a80b33_idx'),
        ),
    ]
